//Api Requests

export const SET_API_ON_FETCHING = "SET_API_FETCHING";
export const SET_API_ON_SUCCESS = "SET_API_ON_SUCCESS";
export const SET_API_ON_FAILED = "SET_API_ON_FAILED";

//API JIKAN Requests

export const SET_APIJIKAN_ON_FETCHING = "SET_APIJIKAN_ON_FETCHING";
export const SET_APIJIKAN_ON_SUCCESS = "SET_APIJIKAN_ON_SUCCESS";
export const SET_APIJIKAN_ON_FAILED = "SET_APIJIKAN_ON_FAILED";
export const SET_APIJIKAN_MORE_ID_FETCHING = "SET_APIJIKAN_MORE_ID_FETCHING";
export const SET_APIJIKAN_MORE_ID_SUCCESS = "SET_APIJIKAN_MORE_ID_SUCCESS";
export const SET_APIJIKAN_MORE_ID_FAILED = "SET_APIJIKAN_MORE_ID_FAILED";
